exclude: "tests/data"
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        args: [--quiet]
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports==1.10.1]
-   repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
    -   id: pylint
        args: ["--disable=import-error"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
-   repo: local
    hooks:
      - id: pydocstringformatter
        name: pydocstringformatter
        entry: pydocstringformatter
        language: system
        types: [python]
        args: ["--write"]
